-- AlterTable
ALTER TABLE "Answers" ALTER COLUMN "content" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Categories" ALTER COLUMN "name" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "description" SET DATA TYPE VARCHAR(500);

-- AlterTable
ALTER TABLE "Questions" ALTER COLUMN "title" SET DATA TYPE VARCHAR(300),
ALTER COLUMN "subject" SET DATA TYPE VARCHAR(300),
ALTER COLUMN "content" SET DATA TYPE TEXT;
